server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://121.43.97.121:3306/questionnaire?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Kevin@1221
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.kevin: debug
    org.springframework.web: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger配置 生产环境禁止访问
springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: false
  api-docs:
    path: /v3/api-docs
    enabled: false
  packages-to-scan: com.kevin.controller

# 短信配置（预留）
#sms:
#  provider: aliyun  # 短信服务商：aliyun, tencent, huawei
#  access-key-id: your-access-key-id
#  access-key-secret: your-access-key-secret
#  sign-name: 问卷系统
#  template-code: SMS_123456789